metadata:
  annotations:
    run.googleapis.com/ingress: internal-and-cloud-load-balancing
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '20'
        run.googleapis.com/vpc-access-connector: cloudrun-vpc-connector-03
        run.googleapis.com/vpc-access-egress: all-traffic
    spec:
      containerConcurrency: 20
      containers:
        - env:
            - name: D1_SITE
              value: day1
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config.day1co.io
            - name: SPRING_CLOUD_CONFIG_NAME
              value: cornerstone
            - name: SPRING_CLOUD_CONFIG_PROFILE
              value: production
            - name: NODE_ENV
              value: prod
          resources:
            limits:
              cpu: 2000m
              memory: 1024Mi
