# setup
FROM node:18-alpine AS builder
WORKDIR /app
COPY .  ./

ARG GITHUB_TOKEN
ENV GITHUB_TOKEN=$GITHUB_TOKEN

RUN echo //npm.pkg.github.com/:_authToken=\${GITHUB_TOKEN} >> ~/.npmrc

RUN npm ci && \
    npm run build && \
    npm prune --omit=dev

FROM node:18-alpine
WORKDIR /app

EXPOSE 8080

ARG NODE_ENV
ENV NODE_ENV=$NODE_ENV

COPY package.json  .
COPY --from=builder /app/lib ./lib/
COPY --from=builder /app/node_modules ./node_modules/

CMD ["npm", "start"]
