#!/bin/bash

# Abort the script at the first error
set -e
#  Causes a pipeline to return the exit status of the last command in the pipe that returned a non-zero return value.
set -o pipefail

COMMAND="$1"
if [ "$COMMAND" = "help" ] || [ "$COMMAND" = "" ]; then
  echo "Deployment Script"
  echo ""
  echo "Usage:"
  echo "  ./ctask command task-env-file-path"
  echo ""
  echo "Example:"
  echo "./ctask deploy ./deploy-dev.env"
  echo "./ctask deploy ./nodejs-sample/deploy/deploy-dev.env"
  echo ""
  echo "Available commands:"
  echo "  deploy - deploys the task to the specified environment"
  echo "  undeploy - undeploys the task from the specified environment"
  echo "  redeploy - same as undeplay && deploy"
  echo "  publish - publish message"
  echo "  mock - deploy for custom public endpoint (may use ngrok)"
  echo "  unmock - undeploy for custom public endpoint"
  echo "  topic-info - displays the topic name for the task"
  echo "  urls - displays the URLs for the task"
  echo "  help - displays this help message"
  exit 0
fi

DEPLOY_DIR="$(dirname -- $(readlink -f "$0"))/deploy"
TASK_ENV_DIR=$(dirname -- $(readlink -f "$2"))
TASK_DIR=$(dirname -- "${TASK_ENV_DIR}")
TASK_ENV_FILE=$(basename -- "$2")

# Ctrl+C to exit
trap "echo The script is terminated; (popd >/dev/null); exit" SIGINT

# ENV file 내에서 경로를 상대경로로 명시하기 위해 pushd/popd 를 사용한다.
pushd "$TASK_ENV_DIR" >/dev/null
# 함수 로드
source "$DEPLOY_DIR/lib.sh"
# 기본값 로드
source "$DEPLOY_DIR/default.env"
# TASK_ENV_FILE 오버라이드
source "$TASK_ENV_FILE"

# export for GCLOUD CLI
export CLOUDSDK_CORE_PROJECT CLOUDSDK_RUN_REGION CLOUDSDK_ARTIFACTS_LOCATION

if [ -f "$CLOUD_RUN_SERVICE_OVERRIDE_FILE" ]; then
  CLOUD_RUN_SERVICE_OVERRIDE_FILE=$(readlink -f "$CLOUD_RUN_SERVICE_OVERRIDE_FILE")
fi

if [ -f "$SUBSCRIPTION_FLAGS_FILE" ]; then
  SUBSCRIPTION_FLAGS_FILE=$(readlink -f "$SUBSCRIPTION_FLAGS_FILE")
fi

if [ -f "$SCHEDULER_FLAGS_FILE" ]; then
  SCHEDULER_FLAGS_FILE=$(readlink -f "$SCHEDULER_FLAGS_FILE")
fi

# $D1_ENV, $D1_SITE 변수는 필수값, 없으면 오류를 발생시킨다
D1_SITES=(day1 fastcampus coloso colosous colosojp crater zerobase bemydoctor motiontribe lmsadmin b2bmarketing lxp
  mylight newspresso wannaspeak)

# D1_ENV 는 로컬에서 각 개발자 임의로 설정할 수 있기 때문에 값의 존재 여부만 판단한다.
if [ -z "$D1_ENV" ]; then
  echo "D1_ENV is not set. Please set D1_ENV in $TASK_ENV_FILE"
  exit 1
fi

if [ "$(validate_array_in "$D1_SITE" "${D1_SITES[@]}")" != true ]; then
  # shellcheck disable=SC2145
  echo "D1_SITE is not valid. Valid values are ${D1_SITES[@]}, but ${D1_SITE} is given."
  exit 1
fi

# Use for cloud-cloud-run-service.default.yml
export D1_ENV D1_SITE

popd >/dev/null

pushd "$TASK_ROOT" >/dev/null

shift
shift

if [ "$COMMAND" == "deploy" ]; then
  _deploy
  print_urls
elif [ "$COMMAND" == "undeploy" ] || [ "$COMMAND" == "unmock" ]; then
  _undeploy
elif [ "$COMMAND" == "redeploy" ]; then
  _undeploy
  _deploy
  print_urls
elif [ "$COMMAND" == "info" ]; then
  _info
elif [ "$COMMAND" == "urls" ]; then
  print_urls
elif [ "$COMMAND" == "publish" ]; then
  _publish "$@"
elif [ "$COMMAND" == "mock" ]; then
  _mock
else
  echo "Invalid command: $COMMAND"
  exit 1
fi
popd >/dev/null
