metadata:
  annotations:
    run.googleapis.com/ingress: internal-and-cloud-load-balancing
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '${RUN_MIN_SCALE}'
        autoscaling.knative.dev/maxScale: '${RUN_MAX_SCALE}'
        run.googleapis.com/vpc-access-connector: ${RUN_VPC_CONNECTOR}
        run.googleapis.com/vpc-access-egress: all-traffic
    spec:
      containerConcurrency: ${CONCURRENCY}
      containers:
        - env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: ${SPRING_CLOUD_CONFIG_URI}
            - name: SPRING_CLOUD_CONFIG_NAME
              value: ${SPRING_CLOUD_CONFIG_NAME}
            - name: SPRING_CLOUD_CONFIG_PROFILE
              value: ${SPRING_CLOUD_CONFIG_PROFILE}
            - name: NODE_ENV
              value: ${NODE_ENV}
            - name: SOME_VARIABLE
              value: ${SOME_VARIABLE}
          resources:
            limits:
              cpu: ${RUN_CPU}
              memory: ${RUN_MEMORY}
